### ISSUE TITLE
Multiprocessing

### ISSUE THREAD

**Issue by ArvinSKushwaha** [samhiner/memorybot#1]
In threadtesting.py I notice you're using hardcoded threading. Perhaps by using the multiprocessing module with a pool and using multiprocessing.cpu_count() to find the number of useable cores for the pooling, you can make it more efficient.

**Comment by samhiner** [comment]
Thanks for the advice. I'll check out if multiprocessing provides a solid performance benefit the way I am planning on using it when I integrate it into my system.
